### PR TITLE
Add `With` combinator to wrap fields with newtypes

### PR DESCRIPTION
**Pull request by maksbotan**

### CODE REVIEW

**Comment by maksbotan** [comment]
Is there a hope to get this merged of we should better fork the package?

**Comment by carymrobbins** [comment]
Yes, just merged it. I wanted to add a test case, so I did that before merging to master. Thanks!

**Comment by maksbotan** [comment]
Thanks! When can we expect a Hackage release?

**Comment by carymrobbins** [comment]
Just now - http://hackage.haskell.org/package/generic-override-0.2.0.0/docs/Data-Override.html#t:With

**Comment by maksbotan** [comment]
Awesome, thanks! :)

**Pull request merged**
